import { prisma } from "@/lib/prisma";
import { sendEmail, billGeneratedEmail } from "@/lib/email";

/**
 * Bulk generates monthly bills for all active student assignments.
 * Can be triggered manually by Super Admin or automatically via Cron.
 * 
 * @param month Current month (1-12)
 * @param year Current year (e.g. 2026)
 * @param generatedBy User ID of the admin triggering this, or "SYSTEM_CRON"
 * @returns Number of bills successfully generated
 */
export async function generateBulkBills(month: number, year: number, generatedBy: string = "SYSTEM_CRON"): Promise<number> {
  const today = new Date();

  // Find all active hostel assignments
  const activeAssignments = await prisma.hostelAssignment.findMany({
    where: { status: "ACTIVE" },
    include: {
      user: {
        include: {
          studentProfile: true,
          rentConfigs: { where: { effectiveTo: null } },
          bedAssignments: { where: { status: "ACTIVE" }, include: { bed: true } },
          roomAssignments: { where: { status: "ACTIVE" } }
        }
      },
      hostel: {
        include: {
          establishmentFees: { where: { effectiveTo: null } },
          bedFees: { where: { effectiveTo: null } }
        }
      }
    }
  });

  let generatedCount = 0;

  for (const assignment of activeAssignments) {
    const student = assignment.user;
    const hostel = assignment.hostel;

    // Check if bill already exists for this month
    const existingBill = await prisma.bill.findUnique({
      where: {
        userId_hostelId_month_year: {
          userId: student.id,
          hostelId: hostel.id,
          month,
          year
        }
      }
    });

    if (existingBill) continue; // Skip if already generated

    // ── Calculate Base Rent (monthly, always applied) ──
    const currentRentConfig = student.rentConfigs.find(rc => rc.hostelId === hostel.id);
    const rentAmount = currentRentConfig ? currentRentConfig.amount.toNumber() : 0;

    // ── Calculate Establishment Fee (ONE-TIME per hostel) ──
    let estFeeAmount = 0;
    const estFeeConfig = hostel.establishmentFees[0];
    if (estFeeConfig) {
      const alreadyChargedEstFee = await prisma.bill.findFirst({
        where: {
          userId: student.id,
          hostelId: hostel.id,
          establishmentFee: { gt: 0 },
        }
      });

      if (!alreadyChargedEstFee) {
        estFeeAmount = estFeeConfig.amount.toNumber();
      }
    }

    // ── Calculate Bed Fee (YEARLY) ──
    let bedFeeAmount = 0;
    const activeBed = student.bedAssignments[0]?.bed;
    const activeRoom = student.roomAssignments[0]?.roomId;

    if (hostel.bedFees.length > 0) {
      const bedSpecificFee = activeBed ? hostel.bedFees.find(f => f.bedId === activeBed.id) : null;
      const roomSpecificFee = activeRoom ? hostel.bedFees.find(f => f.roomId === activeRoom && !f.bedId) : null;
      const hostelSpecificFee = hostel.bedFees.find(f => !f.bedId && !f.roomId);

      const applicableBedFee = bedSpecificFee || roomSpecificFee || hostelSpecificFee;
      if (applicableBedFee) {
        const alreadyChargedBedFee = await prisma.bill.findFirst({
          where: {
            userId: student.id,
            year: year,
            bedFee: { gt: 0 },
          }
        });

        if (!alreadyChargedBedFee) {
          bedFeeAmount = applicableBedFee.amount.toNumber();
        }
      }
    }

    const totalAmount = rentAmount + estFeeAmount + bedFeeAmount;
    
    // Due Date: 7th of the current month, or 7 days from now if already past the 7th
    let dueDate = new Date(year, month - 1, 7);
    if (dueDate < today) {
      dueDate = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);
    }

    await prisma.bill.create({
      data: {
        userId: student.id,
        hostelId: hostel.id,
        month,
        year,
        rentAmount,
        establishmentFee: estFeeAmount,
        bedFee: bedFeeAmount,
        messCharge: 0,
        lateFee: 0,
        totalAmount,
        dueDate,
        status: "GENERATED",
        generatedBy
      }
    });

    // Send email notification
    const studentName = student.studentProfile?.fullName || student.username;
    const monthName = new Date(year, month - 1).toLocaleString('default', { month: 'long' });
    sendEmail({
      to: student.email,
      subject: `Monthly Bill Generated: ${monthName} ${year} - Mirror Hostels`,
      html: billGeneratedEmail(studentName, monthName, year, totalAmount.toFixed(2)),
      userId: student.id,
      type: "BILL_GENERATED"
    }).catch(err => console.error("Failed to send bill email to", student.email, err));

    generatedCount++;
  }

  // Find a super admin for audit log if generated by cron
  let auditUserId = generatedBy;
  if (generatedBy === "SYSTEM_CRON") {
    const admin = await prisma.user.findFirst({ where: { role: "SUPER_ADMIN" }});
    if (admin) auditUserId = admin.id;
  }

  if (generatedCount > 0) {
    await prisma.auditLog.create({
      data: {
        userId: auditUserId,
        action: "GENERATE_MONTHLY_BILLS",
        entity: "Bill",
        newValues: { month, year, generatedCount, trigger: generatedBy }
      }
    });
  }

  return generatedCount;
}
